#!/bin/bash
CAMTYPE="StereoVIO"
if [[ $1 != ""  ]]; then
    CAMTYPE=$1
fi
SHELLNAME="./SetEuRoCVIO_Once.sh"

cd ~/zzh/VIEO_SLAM/Examples/RunEuRoC

OFFSET=0.
EUROCFILE=V101easy
EUROCFILE2=V101
source $SHELLNAME $CAMTYPE $EUROCFILE $EUROCFILE2 $OFFSET &

EUROCFILE=V102medium
EUROCFILE2=V102
source $SHELLNAME $CAMTYPE $EUROCFILE $EUROCFILE2 $OFFSET &

OFFSET=-0.2
EUROCFILE=V201easy
EUROCFILE2=V201
source $SHELLNAME $CAMTYPE $EUROCFILE $EUROCFILE2 $OFFSET &

EUROCFILE=V202medium
EUROCFILE2=V202
source $SHELLNAME $CAMTYPE $EUROCFILE $EUROCFILE2 $OFFSET &

wait

EUROCFILE=V203difficult
EUROCFILE2=V203
source $SHELLNAME $CAMTYPE $EUROCFILE $EUROCFILE2 $OFFSET

OFFSET=0.2
EUROCFILE=MH04difficult
EUROCFILE2=MH04
source $SHELLNAME $CAMTYPE $EUROCFILE $EUROCFILE2 $OFFSET

OFFSET=0.
EUROCFILE=V103difficult
EUROCFILE2=V103
source $SHELLNAME $CAMTYPE $EUROCFILE $EUROCFILE2 $OFFSET

OFFSET=0.2
EUROCFILE=MH05difficult
EUROCFILE2=MH05
source $SHELLNAME $CAMTYPE $EUROCFILE $EUROCFILE2 $OFFSET

EUROCFILE=MH01easy
EUROCFILE2=MH01
source $SHELLNAME $CAMTYPE $EUROCFILE $EUROCFILE2 $OFFSET &

EUROCFILE=MH02easy
EUROCFILE2=MH02
source $SHELLNAME $CAMTYPE $EUROCFILE $EUROCFILE2 $OFFSET &

EUROCFILE=MH03medium
EUROCFILE2=MH03
source $SHELLNAME $CAMTYPE $EUROCFILE $EUROCFILE2 $OFFSET &

SUBFILE=$CAMTYPE
SHELLNAME="./printResultATE.sh"

EUROCFILE=V101easy
source $SHELLNAME $EUROCFILE $SUBFILE
EUROCFILE=V102medium
source $SHELLNAME $EUROCFILE $SUBFILE
EUROCFILE=V201easy
source $SHELLNAME $EUROCFILE $SUBFILE
EUROCFILE=V202medium
source $SHELLNAME $EUROCFILE $SUBFILE
EUROCFILE=V203difficult
source $SHELLNAME $EUROCFILE $SUBFILE
EUROCFILE=MH04difficult
source $SHELLNAME $EUROCFILE $SUBFILE
EUROCFILE=V103difficult
source $SHELLNAME $EUROCFILE $SUBFILE
EUROCFILE=MH05difficult
source $SHELLNAME $EUROCFILE $SUBFILE
EUROCFILE=MH01easy
source $SHELLNAME $EUROCFILE $SUBFILE
EUROCFILE=MH02easy
source $SHELLNAME $EUROCFILE $SUBFILE
EUROCFILE=MH03medium
source $SHELLNAME $EUROCFILE $SUBFILE

exit

